[package]
name = "http-s3-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }
rust-s3 = "0.35"
env_logger = "0.11"
log = "0.4"
dotenv = "0.15"
