name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.os.target }}
          override: true

      - name: Audit Dependencies
        run: cargo audit

      - name: Build
        run: cargo build --release --target ${{ matrix.os.target }}

      - name: Package binary
        run: |
          mkdir dist
          cp target/${{ matrix.platform.target }}/release/http-s3-proxy dist/
          cd dist
          tar -czvf ${{ matrix.platform.target }}.tar.gz http-s3-proxy
        shell: bash

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os.target }}-artifacts
          path: target/${{ matrix.os.target }}/release

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ matrix.os.target }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN_PERMISSIONS: write:packages
